### ISSUE TITLE
ensure dapp uses HOPR api v2

### ISSUE THREAD

**Issue by nionis** [vanoob404/hopr-fsdapp#1]
Through the demo video, I can see that you need to insert 2 API URLs, one for REST API and one for WS API, this is how it worked during API v1.
Could you update the dapp to use the latest API v2?

**Comment by 0xVaibhav11** [comment]
I tried that but it gives error 502 I don't know why. that's why I m taking that directly.
could you help me?

but today is the last day 😥.

**Comment by nionis** [comment]
hey @vanoob404, the deadline for latest contest is around September, so no worries.
What gives u error 502? got any screenshots?

**Comment by 0xVaibhav11** [comment]
> 

@nionis i m getting 502 on fetching **wsEndpoint** from rest API

![Screenshot 2022-07-26 171518](https://user-images.githubusercontent.com/97467803/180999883-2ca73dfa-b6d3-4a4b-b051-d734db718574.jpg)

and on swagger too

![Screenshot 2022-07-26 173515](https://user-images.githubusercontent.com/97467803/181001896-f13386c6-0013-46fe-ae81-44a84d089fec.jpg)


## my code

![Screenshot 2022-07-26 172543](https://user-images.githubusercontent.com/97467803/181000132-750ebd58-579f-4496-8ca1-24e69e521412.jpg)

**Comment by 0xVaibhav11** [comment]
@nionis

**Comment by nionis** [comment]
you cannot fetch a WS endpoint, please take a look on how WS works
for example, check out: https://github.com/hoprnet/hopr-community/blob/main/projects/hopr-status-board/src/useWebSocket.ts

**Comment by 0xVaibhav11** [comment]
@nionis 
I meant only on fetching `/api/massages/websocket` it throws 502 not on else like address or messages

**Comment by 0xVaibhav11** [comment]
I m exhausted. I have tried all things.
plz, tell me how to make the connection with node to collect received msg from node

may I replace **https**://1**33**01 with **wss**://1**95**01

@nionis tell me what can I do???

**Comment by nionis** [comment]
Sorry @vanoob404, can't help you with that. Why don't you take a break and come back to it another day? As I said before, the deadline is in September.

**Comment by 0xVaibhav11** [comment]
I think I misunderstood you.
what do you mean by upgrading dApp to APIv2?

@nionis

**Comment by 0xVaibhav11** [comment]
I m using apiv2 then why are you saying to upgrade. Plzz explain me I m unable to understand.

Are you saying to remove wsendpoint input?
If then how to collect msg from node

And I m trying to get it from `/api/v2/massages/websocket `then it throws 502, what to do.

Plzz reply @nionis

**Comment by 0xVaibhav11** [comment]
@nionis what happened why r you not replying? are you busy!

**Comment by nionis** [comment]
hey @vanoob404, you are incorrectly using the API, see https://github.com/vanoob404/hopr-fsdapp/issues/1#issuecomment-1195463887

**Comment by nionis** [comment]
take a look how WS is used in this project https://github.com/hoprnet/hopr-boomerang-chat (https://github.com/hoprnet/hopr-boomerang-chat/blob/a89d3f697c3663d22e034ed3f7979ccc2ce27d2d/src/App.tsx#L86)

**Comment by 0xVaibhav11** [comment]
It was done 😎.

My PC's modem was not working, then I changed the whole motherboard.
that's why!
